mysql:
  container_name: mysql
  build: ./mysql/
  ports: 
    - "3306:3306"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
mongotest:
  container_name: mongotest
  image: mongo:3.2.1
  ports:
    - "27017:27017"
mongorestore:
  container_name: mongorestore
  build: ./mongoRestore/
  links:
    - mongotest:mongotest
  command: /tmp/entrypoint.sh